name: image_focal_aligner
description: "A Flutter package for aligning images dynamically based on a focal point, with scaling and shifting support."
version: 0.0.1
homepage: https://github.com/your-username/image_focal_aligner # Укажи ссылку на репозиторий или документацию

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=3.0.0" # Flutter 1.17.0 уже очень старый, лучше повысить

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: